[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
; db_name is set via -d flag at runtime
without_demo = all
log_level = test
logfile = False
